.github/workflows/preview-cd.yml, .github/workflows/production-cd.yml
vercel cd를 추가하고 gha-tools를 추가합니다.
=> vercel preview, production에 대한 cd를 추가합니다.

.github/workflows/preview-cd.yml, .github/workflows/production-cd.yml
github package registry를 위한 npmrc를 설정 합니다.
=> cd에 npmrc를 추가합니다.

.github/workflows/production-cd.yml
discord bot의 COLOR형태가 integer로 지원하기에 string hex 형식을 변경합니다.
=> color hex를 integer 형태로 변경

.github/workflows/production-cd.yml
수정된 gha-tools에 맞춰 cd 변경합니다.
- short_sha 추가
- repositry url env추가
=> 수정된 gha-tools에 맞춰 cd 변경

app/_components/topic.tsx, app/_shared/heading/heading.tsx, app/_shared/heading/index.ts, app/wiki/[topic]/page.tsx
heading component를 추가합니다.
- h1 ~ h6까지의 컴포넌트 구현
=> 기본 heading component 들을 추가합니다.

.gitignore, .storybook/decorator.tsx, .storybook/main.ts, .storybook/preview.ts, .vscode/settings.json, app/_shared/accordion/accordion.stories.tsx, package.json, pnpm-lock.yaml, tsconfig.node.json
추후에 컴포넌트 작업의 용이함을 위해 스토리북을 설정합니다.
- storybook main, preview, decorator 설정
- accordion에 대한 스토리 예시 작성
- 나중에 next/navigation을 Import하는 컴포넌트를 사용하실떄는 meta의 parameters에 다음과 같이 넣어주세요.
```jsx
parameters: {
nextjs: {
appdir: true
}
}
```
=> 스토리북 설정을 추가합니다.

app/_components/layout/header.tsx, app/_styles/global-style.tsx, app/layout.tsx, app/page.tsx, app/wiki/[topic]/layout.tsx, pnpm-lock.yaml
페이지에 공통으로 쓰일 헤더 컴포넌트를 제작하였습니다.
DevWiki 글자를 누를 시 메인 페이지로 이동하게 되어있습니다.
Link태그로 페이지 이동 시 리렌더링을 해야지만 헤더가 보이는 버그가 있습니다.
=> feat : 공통 헤더 컴포넌트 제작

app/layout.tsx, package-lock.json, package.json
Next.js에서 제공하는 써드파티 라이브러리를 설치하여 GA4를 연동하였습니다.
[구글애널리틱스, 구글서치콘솔 연동하기. Issue#19](https://github.com/dev-wiki-kr/dev-wiki/issues/19)
참고자료 : [Next.js 공식문서 - 타사 라이브러리](https://nextjs.org/docs/app/building-your-application/optimizing/third-party-libraries)
`@next/third-parties@lastest` 설치
app/layout.tsx `import { GoogleAnalytics } from '@next/third-parties/google'`
head 에 `<GoogleAnalytics gaId="G-MTBJ5VNE9S" />` 삽입
- 구글태그매니저를 연동 & 커스텀 이벤트를 연동하는 것도 있음.
- 이것은 추후 수집할 데이터를 명확하게 세운 뒤 적용할 필요가 있음.
- 다른 자료를 찾아보니, GA4 ID를 env 파일에 환경 변수로 저장하는 방식도 있음 ([블로그](https://coyo-hm.github.io/post/nextjs-gtag), [next.js 예제](https://github.com/vercel/next.js/tree/canary/examples/with-google-analytics))
=> feat: GA4 연동

app/_components/layout/header.tsx, app/_components/topic.tsx, app/_shared/heading/heading.tsx, app/_styles/global-style.tsx, app/_styles/media.tsx
모바일 반응형 로직 및 기본설정을 추가하였습니다.
공통 H 스타일과 topic 레이아웃에 변경이 있었습니다.
모바일 사이즈를 768px로 잡았습니다. 모바일 사이즈에 대한 논의가 조금 필요할 것 같습니다!
공유하기 버튼과 목차가 추후에 들어갈 예정입니다. 그전까지는 본문의 top margin를 그대로 유지하겠습니다.
=> feat : 모바일 반응형 추가

next.config.js
=> redirects 문 제거

pnpm-lock.yaml
pnpm-lock에 충돌이 나 cd가 깨지는 문제를 수정합니다.
=> pnpm lock파일을 업데이트합니다.

app/_service/post/index.ts, app/api/revalidate/route.ts, app/post/[topic]/layout.tsx, app/post/[topic]/page.tsx, envs/.env.development, envs/.env.production
isr을 이용하여 글을 조회할 수 있도록 하며, on demand 방식으로 글의 추가, 변경이 있을때마다 cache invalidation을 하여 최신화를 하도록 합니다.
- isr을 이용한 글 조회추가
- api와 연결하여 글 부를 수 있도록 추가
https://github.com/dev-wiki-kr/dev-wiki-api/pull/17 -> nestjs 에서와 nextjs의 route handler와 연결한 pr입니다.
=> 글을 api를 통해 조회하고 isr로 렌더링 하도록 합니다.

.github/workflows/cd.yml
환경변수 처리를 추가합니다.
- dev-wiki-kr/gha-tools 를 이용한 cd 구축
=> 환경 변수 cd 추가

app/_components/search/search-result-popover/search-result-popover.tsx, app/_service/search/index.ts
한글자, 한 글자 검색할때마다 잠깐 생기는 isLoading 상태때문에 깜빡거리면서 검색되는 기능을 수정했습니다.
- prevData를 이용하여 isLoading상태일때는 지난 결과값을 렌더링 하도록 수정
=> 검색할때 로딩시 좀 더 자연스럽게 나오도록 수정

app/sitemap.ts
sitemap이 promise로 return 되어 제대로 되지 않던 문제를 수정합니다.
=> sitemap 수정

app/_components/auth/login-link.tsx, app/_components/layout/footer.tsx, app/_components/layout/header.tsx, app/_components/main/main-page.tsx, app/_components/not-found.tsx, app/_components/search/header-search/header-desktop-search.tsx, app/_components/search/header-search/header-mobile-search.tsx, app/_components/search/main-search/main-search.tsx, app/_components/search/search-result-popover/search-result-popover.tsx, app/_external/styled-components.tsx, app/_shared/bottom-sheet/bottom-sheet-content.tsx, app/_shared/heading/heading.tsx, app/_shared/link/external-link.tsx, app/_shared/link/internal-link.tsx, app/_shared/toc/toc-side.tsx, app/_styles/style.d.ts, app/_styles/styled.d.ts, app/_styles/theme.ts, app/layout.tsx
close #82 
design token 세팅 작업을 했습니다.
형준님이 만들어주신 디자인 시스템 기반으로 작업했습니다.
- colors, typo 토큰 추가
- styled-component의 지원을 받기 위한 client wrapper 추가
- global style, theme provider와 children을 StyledComponentsRegistry로 래핑해 root layout에 사용했습니다.
- 기존 코드에 colors, typo 토큰 적용
=> feat: design token 세팅

app/_shared/heading/heading.tsx
h1~h6가 2줄이 될때 겹쳐보이는 문제가 있어 line-height를 추가합니다.
=> heading에 line-height 추가

app/_components/auth/login-link.tsx, app/_service/auth/index.ts, app/_service/post/index.ts, app/_service/post/recent-documents.ts, app/_service/search/index.ts, app/post/[topic]/components/markdown-main-content.tsx, app/sitemap.ts, envs/.env.development, envs/.env.production
개발환경에서는 dev url을 바라볼 수 있도록 환경변수를 설정합니다.
=> 환경 변수 처리 추가

.github/workflows/cd.yml
dev 브랜치에서도 release가 돌 수 있도록 설정합니다.
=> 개발환경을 위한 github action을 설정합니다.

.github/workflows/cd.yml
ec2 key의 secret에 줄바꿈이 들어가 있어 이에대한 eof처리를 진행합니다.
=> ec2 key에 대해 줄바꿈 처리

.github/workflows/cd.yml
=> ssh action version 수정

.github/workflows/cd.yml
=> apply boy 버전 수정

Dockerfile
dockerfile에서 .env.production을 읽을 수 있도록 설정합니다.
=> dockerfile env 추가

.github/workflows/cd.yml
=> github action의 환경변수를 테스트합니다.

.github/workflows/cd.yml
=> github action에서 .env를 주입하는 방식 변경

.github/workflows/cd.yml
=> 환경변수 mv 구문 제거

app/post/[topic]/layout.tsx
=> 잘못 설정되어있는 url 수정
